name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security audit
        run: npm audit --audit-level=moderate
        
      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force
          
      - name: Run tests after update
        run: |
          npm test --if-present
          npm run lint --if-present
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies and fix security vulnerabilities'
          title: 'Weekly Dependency Updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains:
            - Updated npm dependencies
            - Security vulnerability fixes
            - Automated testing passed
            
            Please review the changes before merging.
          branch: dependency-updates
          delete-branch: true
